{
 "title": "Cars Prices",
 "time": { "from": "2014-10-26T20:54:40.882Z", "to": "2015-06-22T17:17:51.411Z" },
 "panels": [
  {
   "title": "Vendas Por Estados",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "cars_sales",
     "rawSql": "SELECT\n    sc.state,\n    sc.latitude,\n    sc.longitude,\n    COUNT(v.vin) AS number_of_sales\nFROM\n    car_prices v\nJOIN\n    state_coordinates sc\nON\n    v.state = sc.state\nWHERE\n    LENGTH(v.state) = 2\n    AND LENGTH(sc.state) = 2\nGROUP BY\n    sc.state, sc.latitude, sc.longitude\nORDER BY\n    number_of_sales DESC;\n"
    }
   ]
  },
  {
   "title": "Vendas",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "dataset": "cars_sales",
     "rawSql": "SELECT\n    saledate AS days,\n    COUNT(*) AS 'Número de Vendas'\nFROM\n    car_prices\nGROUP BY\n    days\nORDER BY\n    days;\n"
    }
   ]
  },
  {
   "title": "Número de Veículos Vendidos por Mês",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "cars_sales",
     "rawSql": "SELECT\n    DATE_FORMAT(saledate, '%M') AS month_name, -- Nome completo do mês\n    COUNT(*) AS number_of_sales\nFROM\n    car_prices\nGROUP BY\n    month_name\nORDER BY\n    number_of_sales DESC;\n"
    }
   ]
  },
  {
   "title": "Preço Médio de Venda por Mês",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "cars_sales",
     "rawSql": "SELECT\n    DATE_FORMAT(saledate, '%M') AS month,\n    AVG(sellingprice) AS preco_medio\nFROM\n    car_prices\nGROUP BY\n    month\nORDER BY\n\tpreco_medio DESC;\n"
    }
   ]
  },
  {
   "title": "Preço Médio de Venda por Ano",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 22 },
   "targets": [
    {
     "dataset": "cars_sales",
     "rawSql": "SELECT\n    DATE_FORMAT(saledate, '%Y') AS years,\n    AVG(sellingprice) AS average_price\nFROM\n    car_prices\nGROUP BY\n    years\nORDER BY\n    years DESC;\n"
    }
   ]
  },
  {
   "title": "Número de Veículos Vendidos por Ano",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 22 },
   "targets": [
    {
     "dataset": "cars_sales",
     "rawSql": "SELECT\n    DATE_FORMAT(saledate, '%Y') AS years,\n    COUNT(*) AS 'Número de Vendas'\nFROM\n    car_prices\nGROUP BY\n    years\nORDER BY\n    years DESC;\n"
    }
   ]
  },
  {
   "title": "20 Marcas Mais Vendidas",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "dataset": "cars_sales",
     "rawSql": "SELECT\n    make as 'Marca',\n    COUNT(vin) AS numero_de_vendas\nFROM\n    car_prices\nWHERE\n    make IS NOT NULL\nGROUP BY\n    make\nORDER BY\n    numero_de_vendas DESC\nLIMIT 20;\n"
    }
   ]
  },
  {
   "title": "20 Veículos Mais Vendidos",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "cars_sales",
     "rawSql": "SELECT\n    make as 'Marca',\n    model as 'Modelo',\n    COUNT(*) AS numero_de_vendas\nFROM\n    car_prices\nGROUP BY\n    make,\n    model\nORDER BY\n    numero_de_vendas DESC\nLIMIT 20;\n"
    }
   ]
  },
  {
   "title": "Preço Médio por Marca e Modelo",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 42 },
   "targets": [
    {
     "dataset": "cars_sales",
     "rawSql": "SELECT\n    make AS 'Marca',\n    model AS 'Modelo',\n    AVG(sellingprice) AS Média\nFROM\n    car_prices\nWHERE\n    sellingprice IS NOT NULL\nGROUP BY\n    make,\n    model\nORDER BY\n    Média DESC;\n"
    }
   ]
  },
  {
   "title": "Preço Mediano por Marca e Modelo",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 42 },
   "targets": [
    {
     "dataset": "cars_sales",
     "rawSql": "WITH RankedPrices AS (\n    SELECT\n        make,\n        model,\n        sellingprice,\n        ROW_NUMBER() OVER (PARTITION BY make, model ORDER BY sellingprice) AS RowAsc,\n        ROW_NUMBER() OVER (PARTITION BY make, model ORDER BY sellingprice DESC) AS RowDesc\n    FROM\n        car_prices\n    WHERE\n        sellingprice IS NOT NULL\n),\nMedianPrices AS (\n    SELECT\n        make,\n        model,\n        AVG(sellingprice) AS median_price\n    FROM\n        RankedPrices\n    WHERE\n        RowAsc = RowDesc\n        OR RowAsc + 1 = RowDesc\n        OR RowAsc = RowDesc + 1\n    GROUP BY\n        make,\n        model\n)\nSELECT\n    make as 'Marca',\n    model as 'Modelo',\n    median_price as 'Mediana'\nFROM\n    MedianPrices\nORDER BY\n    median_price DESC;\n"
    }
   ]
  },
  {
   "title": "MMR x SELLINGPRICE",
   "type": "barchart",
   "description": "10 veículos com as maiores diferenças entre o valor estimado pelo Manheim Market Report (mmr) e o preço de venda (sellingprice)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "cars_sales",
     "rawSql": "SELECT\n    vin,\n    make as 'Marca',\n    model as 'Modelo',\n    sellingprice as 'Preço de Venda',\n    mmr as 'Preço MMR',\n    (sellingprice - mmr) AS diferenca_de_precos\nFROM\n    car_prices\nWHERE\n    mmr IS NOT NULL\n    AND sellingprice IS NOT NULL\nORDER BY\n    diferenca_de_precos DESC\nLIMIT 20;\n"
    }
   ]
  },
  {
   "title": "Odometer vs Preço",
   "type": "xychart",
   "description": "Analisa a relação entre a quilometragem e o preço de venda",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "dataset": "cars_sales",
     "rawSql": "SELECT\n    odometer,\n    sellingprice\nFROM\n    car_prices\nWHERE\n    odometer IS NOT NULL\n    AND sellingprice IS NOT NULL\nORDER BY\n    odometer;\n"
    }
   ]
  },
  {
   "title": "Distribuição de Odometer",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "cars_sales",
     "rawSql": "SELECT\n    CASE\n        WHEN odometer < 10000 THEN '0-10,000 km'\n        WHEN odometer BETWEEN 10000 AND 29999 THEN '10,000-30,000 km'\n        WHEN odometer BETWEEN 30000 AND 49999 THEN '30,000-50,000 km'\n        WHEN odometer BETWEEN 50000 AND 99999 THEN '50,000-100,000 km'\n        WHEN odometer >= 100000 THEN '100,000+ km'\n        ELSE 'Unknown'\n    END AS odometer_range,\n    COUNT(*) AS 'Número de Vendas'\nFROM\n    car_prices\nGROUP BY\n    odometer_range\nORDER BY\n    FIELD(odometer_range, '0-10,000 km', '10,000-30,000 km', '30,000-50,000 km', '50,000-100,000 km', '100,000+ km');\n"
    }
   ]
  },
  {
   "title": "Comparação de Tipos de Corpo: Número de Vendas e Preços Médios",
   "type": "barchart",
   "description": "Comparar o número de vendas e os preços médios para diferentes tipos de corpo",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "cars_sales",
     "rawSql": "SELECT\n    LOWER(body) AS body_type, -- Converte o tipo de corpo para minúsculas\n    COUNT(*) AS numero_de_vendas,\n    AVG(sellingprice) AS 'Média de Preços'\nFROM\n    car_prices\nGROUP BY\n    LOWER(body) -- Agrupa por tipo de corpo convertido para minúsculas\nORDER BY\n    numero_de_vendas DESC; -- Ordena por número de vendas\n"
    }
   ]
  },
  {
   "title": "Tendência de Tipos de Carroceria ao Longo do Ano",
   "type": "barchart",
   "description": "Analisar a tendência de popularidade dos tipos de corpo ao longo do ano.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "dataset": "cars_sales",
     "rawSql": "SELECT\n    LOWER(body) AS body_type, -- Converte o tipo de corpo para minúsculas\n    DATE_FORMAT(saledate, '%Y') AS year, -- Formata a data para ano\n    COUNT(*) AS number_of_sales\nFROM\n    car_prices\nGROUP BY\n    LOWER(body), -- Agrupa por tipo de corpo convertido para minúsculas\n    DATE_FORMAT(saledate, '%Y') -- Agrupa por ano\nORDER BY\n    year;\n"
    }
   ]
  },
  {
   "title": "Análise de Vendas por Tipo de Transmissão",
   "type": "barchart",
   "description": "Comparação de Vendas: Compare o número de vendas e os preços médios para veículos com diferentes tipos de transmissão (manual vs automático).",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "cars_sales",
     "rawSql": "SELECT\n    LOWER(transmission) AS transmission_type, -- Converte o tipo de transmissão para minúsculas\n    COUNT(*) AS number_of_sales, -- Conta o número de vendas\n    AVG(sellingprice) AS average_price -- Calcula o preço médio\nFROM\n    car_prices\nGROUP BY\n    LOWER(transmission) -- Agrupa por tipo de transmissão convertido para minúsculas\nORDER BY\n    number_of_sales DESC; -- Ordena por número de vendas\n"
    }
   ]
  },
  {
   "title": "Tendência de Cores (Ano)",
   "type": "barchart",
   "description": "Variações sazonais na popularidade das cores durante os anos.",
   "gridPos": { "h": 9, "w": 10, "x": 5, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "cars_sales",
     "rawSql": "SELECT\n    LOWER(color) AS vehicle_color, -- Converte a cor para minúsculas\n    DATE_FORMAT(saledate, '%Y') AS year, -- Formata a data para ano\n    COUNT(*) AS number_of_sales\nFROM\n    car_prices\nGROUP BY\n    LOWER(color), -- Agrupa por cor convertida para minúsculas\n    DATE_FORMAT(saledate, '%Y') -- Agrupa por ano\nORDER BY\n    year;\n"
    }
   ]
  },
  {
   "title": "Análise de Vendas por Cor",
   "type": "barchart",
   "description": "Distribuição de Vendas por Cor: Analise qual cor de veículo é mais popular e qual tem o preço médio mais alto.",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "cars_sales",
     "rawSql": "SELECT\n    LOWER(color) AS vehicle_color, -- Converte a cor para minúsculas\n    COUNT(*) AS number_of_sales, -- Conta o número de vendas\n    AVG(sellingprice) AS average_price -- Calcula o preço médio\nFROM\n    car_prices\nGROUP BY\n    LOWER(color) -- Agrupa por cor convertida para minúsculas\nORDER BY\n    number_of_sales DESC; -- Ordena por número de vendas\n"
    }
   ]
  },
  {
   "title": "Distribuição de Vendas por Cor do Interior",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "cars_sales",
     "rawSql": "SELECT\n    LOWER(interior) AS interior_color, -- Converte a cor para minúsculas\n    COUNT(*) AS number_of_sales, -- Conta o número de vendas\n    AVG(sellingprice) AS average_price -- Calcula o preço médio\nFROM\n    car_prices\nGROUP BY\n    LOWER(interior) -- Agrupa por cor convertida para minúsculas\nORDER BY\n    number_of_sales DESC; -- Ordena por número de vendas\n"
    }
   ]
  },
  {
   "title": "Tendência de Cores do Interior",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "cars_sales",
     "rawSql": "SELECT\n    LOWER(interior) AS interior_color, -- Converte a cor para minúsculas\n    DATE_FORMAT(saledate, '%Y') AS year, -- Formata a data para ano\n    COUNT(*) AS number_of_sales\nFROM\n    car_prices\nGROUP BY\n    LOWER(interior), -- Agrupa por cor convertida para minúsculas\n    DATE_FORMAT(saledate, '%Y') -- Agrupa por ano\nORDER BY\n year;\n"
    }
   ]
  }
 ]
}